apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: simple-addition-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.5, pipelines.kubeflow.org/pipeline_compilation_time: '2024-07-22T20:16:04.574746',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A simple pipeline that
      adds two numbers", "inputs": [{"name": "x", "type": "Integer"}, {"name": "y",
      "type": "Integer"}], "name": "Simple Addition Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.5}
spec:
  entrypoint: simple-addition-pipeline
  templates:
  - name: add
    container:
      args: [--a, '{{inputs.parameters.x}}', --b, '{{inputs.parameters.y}}', '----output-paths',
        /tmp/outputs/Output/data]
      command:
      - sh
      - -ec
      - |
        program_path=$(mktemp)
        printf "%s" "$0" > "$program_path"
        python3 -u "$program_path" "$@"
      - |
        def add(a, b):
            print(f"Adding {a} + {b}")
            return a + b

        def _serialize_int(int_value: int) -> str:
            if isinstance(int_value, str):
                return int_value
            if not isinstance(int_value, int):
                raise TypeError('Value "{}" has type "{}" instead of int.'.format(
                    str(int_value), str(type(int_value))))
            return str(int_value)

        import argparse
        _parser = argparse.ArgumentParser(prog='Add', description='')
        _parser.add_argument("--a", dest="a", type=int, required=True, default=argparse.SUPPRESS)
        _parser.add_argument("--b", dest="b", type=int, required=True, default=argparse.SUPPRESS)
        _parser.add_argument("----output-paths", dest="_output_paths", type=str, nargs=1)
        _parsed_args = vars(_parser.parse_args())
        _output_files = _parsed_args.pop("_output_paths", [])

        _outputs = add(**_parsed_args)

        _outputs = [_outputs]

        _output_serializers = [
            _serialize_int,

        ]

        import os
        for idx, output_file in enumerate(_output_files):
            try:
                os.makedirs(os.path.dirname(output_file))
            except OSError:
                pass
            with open(output_file, 'w') as f:
                f.write(_output_serializers[idx](_outputs[idx]))
      image: python:3.8
    inputs:
      parameters:
      - {name: x}
      - name: "y"
    outputs:
      artifacts:
      - {name: add-Output, path: /tmp/outputs/Output/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.5
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": ["--a", {"inputValue": "a"}, "--b", {"inputValue": "b"}, "----output-paths",
          {"outputPath": "Output"}], "command": ["sh", "-ec", "program_path=$(mktemp)\nprintf
          \"%s\" \"$0\" > \"$program_path\"\npython3 -u \"$program_path\" \"$@\"\n",
          "def add(a, b):\n    print(f\"Adding {a} + {b}\")\n    return a + b\n\ndef
          _serialize_int(int_value: int) -> str:\n    if isinstance(int_value, str):\n        return
          int_value\n    if not isinstance(int_value, int):\n        raise TypeError(''Value
          \"{}\" has type \"{}\" instead of int.''.format(\n            str(int_value),
          str(type(int_value))))\n    return str(int_value)\n\nimport argparse\n_parser
          = argparse.ArgumentParser(prog=''Add'', description='''')\n_parser.add_argument(\"--a\",
          dest=\"a\", type=int, required=True, default=argparse.SUPPRESS)\n_parser.add_argument(\"--b\",
          dest=\"b\", type=int, required=True, default=argparse.SUPPRESS)\n_parser.add_argument(\"----output-paths\",
          dest=\"_output_paths\", type=str, nargs=1)\n_parsed_args = vars(_parser.parse_args())\n_output_files
          = _parsed_args.pop(\"_output_paths\", [])\n\n_outputs = add(**_parsed_args)\n\n_outputs
          = [_outputs]\n\n_output_serializers = [\n    _serialize_int,\n\n]\n\nimport
          os\nfor idx, output_file in enumerate(_output_files):\n    try:\n        os.makedirs(os.path.dirname(output_file))\n    except
          OSError:\n        pass\n    with open(output_file, ''w'') as f:\n        f.write(_output_serializers[idx](_outputs[idx]))\n"],
          "image": "python:3.8"}}, "inputs": [{"name": "a", "type": "Integer"}, {"name":
          "b", "type": "Integer"}], "name": "Add", "outputs": [{"name": "Output",
          "type": "Integer"}]}', pipelines.kubeflow.org/component_ref: '{}', pipelines.kubeflow.org/arguments.parameters: '{"a":
          "{{inputs.parameters.x}}", "b": "{{inputs.parameters.y}}"}'}
  - name: simple-addition-pipeline
    inputs:
      parameters:
      - {name: x}
      - name: "y"
    dag:
      tasks:
      - name: add
        template: add
        arguments:
          parameters:
          - {name: x, value: '{{inputs.parameters.x}}'}
          - name: "y"
            value: '{{inputs.parameters.y}}'
  arguments:
    parameters:
    - {name: x}
    - name: "y"
  serviceAccountName: pipeline-runner
