apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: restic
  namespace: velero
  labels:
    app: restic
spec:
  selector:
    matchLabels:
      app: restic
  template:
    metadata:
      labels:
        app: restic
    spec:
      containers:
      - name: restic
        image: velero/velero-restic:v1.6.3
        volumeMounts:
        - mountPath: /hostpath
          name: hostpath
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RESTIC_PASSWORD
          value: "your-really-strong-password"
        securityContext:
          privileged: true
      volumes:
      - name: hostpath
        hostPath:
          path: /mnt/disks
